version: '2'

services:
  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:3
  postgres:
    restart: always
    image: postgres:10
    expose:
      - 5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql
  django:
    restart: always
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    image: scapi:v1
    volumes:
      - .:/django
  worker:
    restart: always
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile
    volumes:
      - .:/django
